### ISSUE TITLE
cannot login tobackend after fresh install

### ISSUE THREAD

**Issue by parabol** [ionize/ionize#185]
i installed without any error twice. i also installed test data, when i try to login(backend or else.), it fails immedately.

**Comment by kstenschke** [comment]
i had the same problem using the current ionize version 1.0.8 checked out from github: installation works but only the home page can be loaded, all rewritten URLs fail (the downloaded version 1.0.7 from http://ionizecms.com/ does not have that problem). 
Solution: edit .htaccess and comment-out line 4 (into: #RewriteBase /) and url rewriting works again.

**Comment by partikule** [comment]
http://doc.ionizecms.com/en/installation/troubleshooting
