### ISSUE TITLE
Admin Page options Fatal error

### ISSUE THREAD

**Issue by adamos42** [ionize/ionize#331]
Fatal error:  Call to a member function result() on boolean in /var/www/ionize107/application/models/base_model.php on line 1333

Fresh git clone, fresh install with sample data and error in page options sidebar.

**Comment by adamos42** [comment]
Ah the problem is the database, missing the table **extend_field_article_type**
@kstenschke Do you have the missing extend_field_article_type table? Can you add a database backup of your working copy?

**Comment by kstenschke** [comment]
Hi Adam,
thanks for looking into this! :) i can only look into it later this week. the table structure is in install/database/database.sql, install/database.xml and in the latest migration sql file. if with the current head revision of the git repository, the installer does not create the table as defined, a conflict during merge might be the reason for these definitions not being used(?)
greetings from zurich, Kay

**Comment by adamos42** [comment]
Thanks @kstenschke , I founded the missing insert. Im added the 1.0.7 => 1.0.8 migration to the Installer script (unfortunately, the existence of the xml file is not enough), now it should be working if somebody migrating the database.

**Comment by kstenschke** [comment]
thank you Adam. great to see the ionize project gain more drive :)
