### ISSUE TITLE
suggestion: dev tag <ion:dev if="development"/>

### ISSUE THREAD

**Issue by sommmen** [ionize/ionize#349]
a tag that would display the status would be really helpfull

 <ion:dev /> //returns the status as string

i got a development.css set that i would be nice to only get included when i'm developing.

**Comment by trk** [comment]
If you try :
```php
echo ENVIRONMENT;
```

What you have result ?

**Comment by sommmen** [comment]
beatifull, that works aswell. 
was a bit obvious lol. thanks for the help.
