### ISSUE TITLE
SEO description and keywords with language

### ISSUE THREAD

**Issue by adamos42** [ionize/ionize#357]
Somehow the keyword and descriptions not working well with multiple language, somehow only the default language seo data used in the meta tags.

Details: http://ionizecms.com/forum/viewtopic.php?id=2176

**Comment by kstenschke** [comment]
I believe this is a local error and not a bug in the recent code. Maybe you migrated an old installation? -I pulled the most recent version from git, did set up a second language and added title, description and keywords in the backend: everything works as expected.

**Comment by adamos42** [comment]
Not was me :) Thanks the informations, I tried out now with the master branch and the 1.0.7.1 also and its working, I dont know what version they use, but the problem is local.
