### ISSUE TITLE
PHP error at: Article > Attributes > Type Dropdown options

### ISSUE THREAD

**Issue by jahller** [ionize/ionize#375]
When you open the options of an article and open the Dropdown Type the following PHP error is shown within the dropdown:

> A PHP Error was encountered

Severity: Notice
Message:  Undefined variable: article_type_current
Filename: article/options.php
Line Number: 117

This is related to the variable article_type_current being commented in the file /application/controllers/admin/article.php on line 777.

**Comment by partikule** [comment]
Corrected
